name: Keep Projects Awake

on:
  workflow_dispatch:

jobs:
  check_projects:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create and Run Project Check Script
        run: |
          echo '#!/bin/bash
          projects=(
              "https://newblog-z1jy.onrender.com"
              "https://noteapp001.onrender.com/"
              "https://satiscraper.onrender.com/"
              "https://smartpdf.onrender.com"
              "https://emochat-latest.onrender.com/"
              "https://projection-4wrw.onrender.com"
          )
          
          for project in "${projects[@]}"; do
              echo "Checking $project"
              response=$(curl -s -o /dev/null -w "%{http_code}" "$project" --max-time 60)
              
              if [ "$response" -eq 200 ]; then
                  echo "Success: $project is up"
              else
                  echo "Failed: $project returned HTTP status $response"
              fi
          done' > check_projects.sh
          
          chmod +x check_projects.sh
          ./check_projects.sh
