name: Scheduled Cron Job

on:
  schedule:
    - cron: '*/1 * * * *'  
  workflow_dispatch: 

jobs:
  run-cronjob:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run script
      run: |
        echo "Running scheduled task..."
        chmod +x ./keepawakejob.sh
        ./keepawakejob.sh
